### ISSUE TITLE
Unable to load library 'NoiseEstimation, win 64, fiji, imagej 1.50a

### ISSUE THREAD

**Issue by chalkie666** [haiderriazkhan/CANDLE-J#1]
java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: Unable to load library 'NoiseEstimation': The specified module could not be found.
when running candle on a small tiff stack image. 
windows 7 64bit, fiji, imagej 1.50a 64 bit, java1,6 bundles in fiji.

Installed as described in docs, but had to change the python file filename to candle_.py
so fiji knows, by the underscore, that its a plugin. 

in the console output

mean: 11.7490854846 minimum: 0.0 maximum: 255.0
number of slices: 33
Preprocessing: 3D Median filter
Elapsed time: 1.32799983025
mean: 8.14309442343 minimum: 0.0 maximum: 255.0
Stabilization: Anscombe transform
Elapsed time: 0.0520000457764
mean: 3.88282227999 minimum: 1.22474491596 maximum: 31.9609127045
Going Native ...
Traceback (most recent call last):
  File "C:\Users\100044~1\PORTAB~1\Fiji.app\plugins\CANDLE-J\CANDLE_.py", line 162, in <module>
    fimg = NativeCodeJNA.NativeCall(InputImgArray, medfiltArray, int(searchradius), int(patchradius), beta , int(x), int(y), int(z))

```
at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:163)

at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:236)

at com.sun.jna.Library$Handler.<init>(Library.java:140)

at com.sun.jna.Native.loadLibrary(Native.java:379)

at com.sun.jna.Native.loadLibrary(Native.java:364)

at NativeCodeJNA.NativeCall(NativeCodeJNA.java:28)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)

at java.lang.reflect.Method.invoke(Method.java:597)
```

java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: Unable to load library 'NoiseEstimation': The specified module could not be found.

**Comment by boazmohar** [comment]
I am getting the same error, any thoughts?

**Comment by boazmohar** [comment]
Solved: add the plugin directory to your 'Path'
[instructions](http://condor.depaul.edu/slytinen/instructions/setupj2sewin7.html)
