### ISSUE TITLE
Crashes on OS X with latest version of Fiji

### ISSUE THREAD

**Issue by raacampbell** [haiderriazkhan/CANDLE-J#5]
I followed [these instructions] to get the plugin installed on OS X (it would be good to put CANDLE on the IJ update site to simplify installation) then ran on an image. I get the following error:

```
Traceback (most recent call last):
  File "CANDLE-J/CANDLE_.py", line 60, in <module>
	at ij.process.StackStatistics.<init>(StackStatistics.java:20)
	at ij.process.StackStatistics.<init>(StackStatistics.java:14)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)

java.lang.NullPointerException: java.lang.NullPointerException
mean: 85.8803741765 minimum: 0.0 maximum: 32511.0
number of slices: 1
Preprocessing: 3D Median filter
Elapsed time: 14.7890000343
mean: 79.8649565372 minimum: 0.0 maximum: 21449.0
Stabilization: Anscombe transform
Elapsed time: 1.257999897
mean: 14.4744590157 minimum: 1.22474491596 maximum: 292.912109375
Going Native ...
Traceback (most recent call last):
  File "CANDLE-J/CANDLE_.py", line 162, in <module>
	at NativeCodeJNA.NativeCall(NativeCodeJNA.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0
mean: 117.564014 minimum: 0.0 maximum: 32767.0
number of slices: 1
Preprocessing: 3D Median filter
Elapsed time: 15.1480000019
mean: 110.808861217 minimum: 0.0 maximum: 28097.0
Stabilization: Anscombe transform
Elapsed time: 1.00999999046
mean: 14.5616233664 minimum: 1.22474491596 maximum: 335.245422363
Going Native ...
Traceback (most recent call last):
  File "CANDLE-J/CANDLE_.py", line 162, in <module>
	at NativeCodeJNA.NativeCall(NativeCodeJNA.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0
```

**Comment by raacampbell** [comment]
I see there is a MATLAB implementation. I'll use that instead, but maybe you care about this issue.
